// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMzNLDBwVK-_R5lV8FMYF12WlBitU9fHU',
    appId: '1:39932065706:web:d3b3ad5e4fe7c4cbfb5dd3',
    messagingSenderId: '39932065706',
    projectId: 'zero-98e8f',
    authDomain: 'zero-98e8f.firebaseapp.com',
    databaseURL: 'https://zero-98e8f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'zero-98e8f.firebasestorage.app',
    measurementId: 'G-2RB78CQQ5R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-dbHKablKtIpz7Hk8pu38dQtcmNCHZvw',
    appId: '1:39932065706:android:74d05a41e9b73de5fb5dd3',
    messagingSenderId: '39932065706',
    projectId: 'zero-98e8f',
    databaseURL: 'https://zero-98e8f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'zero-98e8f.firebasestorage.app',
  );
}
